In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2],[3,4],[5,6]])
print(a)

[1 2 3]


In [3]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
b.ndim

2

In [5]:
a.ndim

1

In [6]:
a.shape
b.shape

(3, 2)

In [7]:
b.shape

(3, 2)

In [8]:
a.shape

(3,)

In [9]:
a.dtype


dtype('int32')

In [10]:
c = np.array([2.3,3.3,4.3])
print(c)
c.dtype

[2.3 3.3 4.3]


dtype('float64')

In [11]:
a.itemsize

4

In [12]:
b.itemsize

4

In [13]:
c.itemsize

8

In [14]:
a.size

3

In [15]:
b.size
c.size

3

In [16]:
c.size

3

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.ones((2,4,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [21]:
np.full((2,3), 77)

array([[77, 77, 77],
       [77, 77, 77]])

In [22]:
np.random.rand(4,2)

array([[0.90472475, 0.20525052],
       [0.58760556, 0.75077027],
       [0.61683735, 0.1949174 ],
       [0.09744453, 0.56869947]])

In [23]:
np.random.randint(7, size=(3,3))

array([[1, 6, 3],
       [0, 0, 2],
       [0, 6, 5]])

In [24]:
np.random.randint(6, size=(3,3))

array([[0, 0, 1],
       [1, 4, 4],
       [5, 0, 0]])

In [27]:
a = np.array([[1,2,3], [2,3,4], [3,4,5]])
print(a)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [28]:
a.ndim

2

In [29]:
a.shape

(3, 3)

In [30]:
a[2,2]

5

In [31]:
a[2,1]

4

In [34]:
#specific row
print(a)
a[1,:]

[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([2, 3, 4])

In [35]:
print(a)
a[:,0]

[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([1, 2, 3])

In [36]:
a[:,1]

array([2, 3, 4])

In [37]:
a[0, 1:-1:2]

array([2])

In [38]:
a = np.array([1,2,3])
b = a
b[1] = 77
print(a)
print(b)

[ 1 77  3]
[ 1 77  3]


In [39]:
c = np.array([1,2,3])
d = c.copy()
d[1] = 77
print(c)
print(d)

[1 2 3]
[ 1 77  3]


In [40]:
a = np.array([1,2,3,4])
print(a + 2)
print(a * 2)
print(a - 2)
print(a / 2)

[3 4 5 6]
[2 4 6 8]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [41]:
b = np.array([1,2,3,4])
a + b

array([2, 4, 6, 8])

In [42]:
a * 2
print(a + b)

[2 4 6 8]


In [43]:
a * 3

array([ 3,  6,  9, 12])

In [45]:
a = np.array([0,1,2,3,4])
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [46]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [50]:
#determinant
c = np.identity(4)
np.linalg.det(c)

1.0

In [52]:
stat = np.array([[1,2,3], [4,5,6]])
np.max(stat)


6

In [53]:
np.min(stat)

1

In [54]:
print(stat)

[[1 2 3]
 [4 5 6]]


In [55]:
np.sum(stat, axis = 0)

array([5, 7, 9])